name: Deploy HireLens to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/app
            git pull origin main

            cd backend
            npm install
            pm2 restart hirelens-backend --update-env || pm2 start server.js --name hirelens-backend

            cd ../frontend
            npm install
            npm run build

            sudo rm -rf /var/www/hirelens/*
            sudo cp -r dist/* /var/www/hirelens/

            sudo systemctl restart nginx
